services:
    galcvua_jwt_refresh.subscriber.store_user_on_login:
        class: Galcvua\JwtRefreshBundle\EventSubscriber\StoreUserOnLoginSubscriber
        arguments:
            $security: '@security.helper'
            $refreshTokenFirewall: '%galcvua_jwt_refresh.refresh_token_firewall%'
            $requestStack: '@request_stack'
        tags:
            - { name: 'kernel.event_subscriber' }
    galcvua_jwt_refresh.subscriber.logout:
        class: Galcvua\JwtRefreshBundle\EventSubscriber\LogoutSubscriber
        tags:
            - { name: 'kernel.event_subscriber' }
    galcvua_jwt_refresh.security.jwt_refresh_authenticator:
        class: Galcvua\JwtRefreshBundle\Security\JwtRefreshAuthenticator
        arguments:
            $locator: '@security.firewall.context_locator'
    galcvua_jwt_refresh.controller.jwt_refresh:
        class: Galcvua\JwtRefreshBundle\Controller\JwtRefreshController
        public: true
        arguments:
            $security: '@security.helper'
            $jwtManager: '@lexik_jwt_authentication.jwt_manager'
